---
- name: Build plex server
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    state: started
    detach: true
    network_mode: host
    env: "{{container_vars.plex.env_vars}}"
    volumes: "{{container_vars.plex.volumes}}"
- name: Build sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    pull: true
    state: started
    detach: true
    env: "{{container_vars.sonarr.env_vars}}"
    ports: "{{container_vars.sonarr.ports}}"
    volumes: "{{container_vars.sonarr.volumes}}"
- name: Build radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: true
    state: started
    detach: true
    env: "{{container_vars.radarr.env_vars}}"
    ports: "{{container_vars.radarr.ports}}"
    volumes: "{{container_vars.radarr.volumes}}"
- name: Build jackett
  docker_container:
    name: jackett
    image: linuxserver/jackett
    pull: true
    state: started
    detach: true
    env: "{{container_vars.jackett.env_vars}}"
    ports: "{{container_vars.jackett.ports}}"
    volumes: "{{container_vars.jackett.volumes}}"
- name: place run-deluge.sh
  template:
    src: templates/run-delugevpn.sh.j2
    dest: "{{container_vars.delugevpn.container_path}}/run-delugevpn.sh"
    owner: "{{user.PID}}"
    group: "{{user.PID}}"
    mode: 0755
- name: Build Deluge server
  shell: "{{container_vars.delugevpn.container_path}}/run-delugevpn.sh"
  ignore_errors: yes
- name: get .ovpn files
  get_url:
    url: https://www.privateinternetaccess.com/openvpn/openvpn.zip
    dest: "{{container_vars.delugevpn.container_path}}/config/openvpn/openvpn.zip"
    mode: 0755
- name: unzip files
  unarchive:
    src: "{{container_vars.delugevpn.container_path}}/config/openvpn/openvpn.zip"
    dest: "{{container_vars.delugevpn.container_path}}/config/openvpn/"
    remote_src: yes
