---
- name: create /tmp/ovpn for files
  file:
    path: "{{ovpn_folder}}"
    state: directory
    mode: 0755
    owner: "{{user.name}}"
    group: wheel
- name: get .ovpn files
  get_url:
    url: https://www.privateinternetaccess.com/openvpn/openvpn.zip
    dest: "{{ovpn_folder}}/"
    mode: 0775
- name: unzip files
  unarchive:
    src: https://www.privateinternetaccess.com/openvpn/openvpn.zip
    dest: "{{ovpn_folder}}/"
    remote_src: yes
- name: Copy each file over that matches the given pattern
  copy:
    src: "{{ovpn_folder}}/{{ item }}"
    dest: "{{container_vars.delugevpn.container_path}}/config/openvpn/"
    owner: "{{user.name}}"
    group: wheel
    mode: 0755
  with_fileglob:
    - /*Netherlands.ovpn
    - /*.crt
    - /*.pem
- name: place run-deluge.sh
  template:
    src: templates/run-delugevpn.sh.j2
    dest: "{{container_vars.delugevpn.container_path}}/run-delugevpn.sh"
    owner: "{{user.PID}}"
    group: "{{user.PID}}"
    mode: 0755
- name: Build Deluge server
  shell: "{{container_vars.delugevpn.container_path}}/run-delugevpn.sh"
  ignore_errors: yes
