---
- name: Build muximux
  docker_container:
    name: muximux
    image: linuxserver/muximux
    pull: true
    state: started
    detach: true
    restart_policy: always
    env:
      PUID: "{{user.PID}}"
      PGID: "{{user.PID}}"
      TZ: CST
    ports:
      - 80:80
    volumes:
      - "{{containers_folder}}/muximux/config:/config"