---
- name: Build Transmission
  docker_container:
    name: transmission
    image: haugene/transmission-openvpn
    pull: true
    state: started
    detach: true
    restart_policy: always
    log_driver: json-file
    log_options:
      max-size: 10m
    env:
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: Sweden
      OPENVPN_USERNAME: '{{pia_user}}'
      OPENVPN_PASSWORD: '{{pia_pass}}'
      WEBPROXY_ENABLED: false
      LOCAL_NETWORK: 192.168.1.0/24
    ports:
      - 9091:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/containers/transmission/data:/data
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun
