---
# vars file for ec3
ovpn_folder: /tmp/ovpn
container_vars:
  plex:
    container_path: /docker/containers/plex/
  delugevpn:
    container_path: /docker/containers/deluge
  sonarr:
    container_path: /docker/containers/sonarr
  radarr:
    container_path: /docker/containers/radarr
  jackett:
    container_path: /docker/containers/jackett
apt_list:
  - docker
  - vim
  - python-pip
  - python3-pip
  - unzip
pip_list:
  - docker-py
  - bottle
  - glances
media_folders:
    movies: /docker/media/movies/
    tv: /docker/media/tv
    tv_manual: /docker/media/tv_manual
user:
  name: andrew
  PID: 1000
